In [2]:
import pandas as pd

In [8]:
df=pd.read_csv('PPGObtained.csv')

In [9]:
df.head()

   Num.  subject_ID Sex(M/F)  Age(year)  Height(cm)  ...  836  837  838  839  840
0     1           2   Female         45         152  ...  0.0  0.0  0.0  0.0  0.0
1     2           3   Female         50         157  ...  0.0  0.0  0.0  0.0  0.0
2     3           6   Female         47         150  ...  0.0  0.0  0.0  0.0  0.0
3     4           8     Male         45         172  ...  0.0  0.0  0.0  0.0  0.0
4     5           9   Female         46         155  ...  0.0  0.0  0.0  0.0  0.0

[5 rows x 855 columns]

In [25]:
dfsig=df[df.columns[14:]]

In [27]:
dfsig.head()

             0            1            2            3  ...  837  838  839  840
0  2295.835256  2295.825631  2295.787559  2295.721146  ...  0.0  0.0  0.0  0.0
1  2032.184944  2032.183809  2032.179923  2032.173293  ...  0.0  0.0  0.0  0.0
2  2039.278795  2039.275898  2039.270052  2039.261257  ...  0.0  0.0  0.0  0.0
3  2088.693675  2088.692026  2088.686638  2088.677519  ...  0.0  0.0  0.0  0.0
4  2048.847053  2048.845220  2048.841250  2048.835148  ...  0.0  0.0  0.0  0.0

[5 rows x 841 columns]

In [28]:
len(dfsig)

628

In [29]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
# Fit on training set only.
scaler.fit(dfsig)
# Apply transform to both the training set and the test set.
dfsigtransform=scaler.transform(dfsig)

In [31]:
dfsigtransform

array([[ 0.40269689,  0.40268707,  0.40260994, ..., -0.76924825,
        -0.76139915, -0.75676117],
       [-0.73988664, -0.73988465, -0.73987531, ..., -0.76924825,
        -0.76139915, -0.75676117],
       [-0.70914396, -0.70914894, -0.70914643, ..., -0.76924825,
        -0.76139915, -0.75676117],
       ...,
       [ 3.09393961,  3.09398673,  3.09410531, ..., -0.76924825,
        -0.76139915, -0.75676117],
       [ 2.66808205,  2.6681273 ,  2.66824694, ..., -0.76924825,
        -0.76139915, -0.75676117],
       [ 2.54551746,  2.54556476,  2.5457055 , ...,  1.85322586,
         1.86791763,  1.88535453]])

In [51]:
from sklearn.decomposition import PCA
# Make an instance of the Model
pca = PCA(.99)

In [52]:
pca.fit(dfsigtransform)

PCA(copy=True, iterated_power='auto', n_components=0.99, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [53]:
pca.n_components_

23

In [54]:
dfpca=pca.transform(dfsigtransform)

In [55]:
dfpca

array([[ 6.76565679e+00, -1.03549206e+01,  2.75825237e+01, ...,
        -1.36224510e+00, -3.52086605e+00, -8.17219588e-01],
       [ 5.30691279e+00, -6.47152302e+00, -3.36537930e+00, ...,
        -9.83960697e-02, -3.02367556e-01,  1.48961757e+00],
       [ 6.97901045e+00, -4.70042300e+00, -4.17428160e+00, ...,
        -8.26787545e-02,  1.32425590e-01, -1.39214465e+00],
       ...,
       [-8.15667756e+01,  2.53006445e+00,  1.11915072e+01, ...,
        -3.55275843e-01, -8.20349264e-01,  5.19227084e-02],
       [-7.03425574e+01,  7.88655775e+00, -3.15509404e+00, ...,
        -1.33760322e-01, -1.10729315e-01, -1.54408798e+00],
       [-7.37702500e+01,  5.24126465e+00, -8.23032168e+00, ...,
        -9.82947324e-02, -2.65107757e-01,  6.62315296e-03]])

In [56]:
dfpca=pd.DataFrame(dfpca)

In [57]:
dfpca

            0          1          2   ...        20        21        22
0     6.765657 -10.354921  27.582524  ... -1.362245 -3.520866 -0.817220
1     5.306913  -6.471523  -3.365379  ... -0.098396 -0.302368  1.489618
2     6.979010  -4.700423  -4.174282  ... -0.082679  0.132426 -1.392145
3     1.429887 -14.176088  16.421794  ... -0.170248 -0.922263  0.402726
4     1.612801  -6.175799  -7.400112  ... -0.005111 -0.218023  1.494879
..         ...        ...        ...  ...       ...       ...       ...
623 -72.673289  -6.774619  22.632062  ...  0.348780  1.018294 -0.022718
624 -36.618051  18.987273   9.084993  ...  0.082435 -0.188499  1.563171
625 -81.566776   2.530064  11.191507  ... -0.355276 -0.820349  0.051923
626 -70.342557   7.886558  -3.155094  ... -0.133760 -0.110729 -1.544088
627 -73.770250   5.241265  -8.230322  ... -0.098295 -0.265108  0.006623

[628 rows x 23 columns]

In [58]:
dffeatures=df[df.columns[0:14]]

In [59]:
dffeatures.head()

   Num.  subject_ID  ... cerebral infarction  cerebrovascular disease
0     1           2  ...                 NaN                      NaN
1     2           3  ...                 NaN                      NaN
2     3           6  ...                 NaN                      NaN
3     4           8  ...                 NaN                      NaN
4     5           9  ...                 NaN                      NaN

[5 rows x 14 columns]

In [60]:
dfcombined=pd.concat([dffeatures,dfpca],axis=1)

In [61]:
dfcombined.head()

   Num.  subject_ID Sex(M/F)  Age(year)  ...        19        20        21        22
0     1           2   Female         45  ... -0.292516 -1.362245 -3.520866 -0.817220
1     2           3   Female         50  ...  1.482329 -0.098396 -0.302368  1.489618
2     3           6   Female         47  ...  0.632844 -0.082679  0.132426 -1.392145
3     4           8     Male         45  ...  1.181526 -0.170248 -0.922263  0.402726
4     5           9   Female         46  ... -1.388358 -0.005111 -0.218023  1.494879

[5 rows x 37 columns]

In [63]:
dfcombined.to_csv('PPG_Final.csv',index=False)