In [1]:
import pandas as pd

In [2]:
# reading the PPG BP dataset
ppg_bp_data1=pd.read_excel('PPG-BP dataset.xlsx',header=1)
ppg_bp_data2=pd.read_excel('PPG-BP dataset.xlsx',header=1)
ppg_bp_data3=pd.read_excel('PPG-BP dataset.xlsx',header=1)

In [3]:
ppg_bp_data1.head()

   Num.  subject_ID Sex(M/F)  ...          Hypertension  Diabetes  cerebral infarction
0     1           2   Female  ...  Stage 2 hypertension       NaN                  NaN
1     2           3   Female  ...  Stage 2 hypertension       NaN                  NaN
2     3           6   Female  ...                Normal       NaN                  NaN
3     4           8     Male  ...       Prehypertension       NaN                  NaN
4     5           9   Female  ...       Prehypertension       NaN                  NaN

[5 rows x 11 columns]

In [4]:
ppg_combained=pd.concat([ppg_bp_data1,ppg_bp_data2,ppg_bp_data3])#Concatenating the three ppg dataframes

In [5]:
ppg_combained.head()

   Num.  subject_ID Sex(M/F)  ...          Hypertension  Diabetes  cerebral infarction
0     1           2   Female  ...  Stage 2 hypertension       NaN                  NaN
1     2           3   Female  ...  Stage 2 hypertension       NaN                  NaN
2     3           6   Female  ...                Normal       NaN                  NaN
3     4           8     Male  ...       Prehypertension       NaN                  NaN
4     5           9   Female  ...       Prehypertension       NaN                  NaN

[5 rows x 11 columns]

In [6]:
ppg_combained.tail()

     Num.  subject_ID Sex(M/F)  ...     Hypertension  Diabetes  cerebral infarction
214   215         415     Male  ...           Normal       NaN                  NaN
215   216         416   Female  ...           Normal       NaN                  NaN
216   217         417     Male  ...  Prehypertension       NaN                  NaN
217   218         418     Male  ...           Normal       NaN                  NaN
218   219         419     Male  ...           Normal       NaN                  NaN

[5 rows x 11 columns]

In [7]:
len(ppg_combained)

657

In [8]:
ppg_combained.to_csv('PPGmain.csv',index=False)

In [9]:
ppg_combained=pd.read_csv('PPGmain.csv')

In [10]:
ppg_combained.head()

   Num.  subject_ID Sex(M/F)  ...          Hypertension  Diabetes  cerebral infarction
0     1           2   Female  ...  Stage 2 hypertension       NaN                  NaN
1     2           3   Female  ...  Stage 2 hypertension       NaN                  NaN
2     3           6   Female  ...                Normal       NaN                  NaN
3     4           8     Male  ...       Prehypertension       NaN                  NaN
4     5           9   Female  ...       Prehypertension       NaN                  NaN

[5 rows x 11 columns]

In [11]:
ppg_combained.tail()

     Num.  subject_ID Sex(M/F)  ...     Hypertension  Diabetes  cerebral infarction
652   215         415     Male  ...           Normal       NaN                  NaN
653   216         416   Female  ...           Normal       NaN                  NaN
654   217         417     Male  ...  Prehypertension       NaN                  NaN
655   218         418     Male  ...           Normal       NaN                  NaN
656   219         419     Male  ...           Normal       NaN                  NaN

[5 rows x 11 columns]

In [12]:
dffeaturessignal=pd.read_csv('fixed_length_features.csv')# reading the fixed length ppg signal features file

In [13]:
dffeaturessignal.drop(dffeaturessignal.columns[[0]], axis=1, inplace=True)

In [14]:
dffeaturessignal.head()

             0            1            2            3  ...  837  838  839  840
0  2295.835256  2295.825631  2295.787559  2295.721146  ...  0.0  0.0  0.0  0.0
1  2032.184944  2032.183809  2032.179923  2032.173293  ...  0.0  0.0  0.0  0.0
2  2039.278795  2039.275898  2039.270052  2039.261257  ...  0.0  0.0  0.0  0.0
3  2088.693675  2088.692026  2088.686638  2088.677519  ...  0.0  0.0  0.0  0.0
4  2048.847053  2048.845220  2048.841250  2048.835148  ...  0.0  0.0  0.0  0.0

[5 rows x 841 columns]

In [15]:
ppg_combained=pd.concat([ppg_combained,dffeaturessignal],axis=1)#Concatenating the Ppg bp dataset with fixed length feature dataframe

In [16]:
ppg_combained.head()

   Num.  subject_ID Sex(M/F)  Age(year)  Height(cm)  ...  836  837  838  839  840
0     1           2   Female         45         152  ...  0.0  0.0  0.0  0.0  0.0
1     2           3   Female         50         157  ...  0.0  0.0  0.0  0.0  0.0
2     3           6   Female         47         150  ...  0.0  0.0  0.0  0.0  0.0
3     4           8     Male         45         172  ...  0.0  0.0  0.0  0.0  0.0
4     5           9   Female         46         155  ...  0.0  0.0  0.0  0.0  0.0

[5 rows x 852 columns]

In [17]:
ppg_combained.tail()

     Num.  subject_ID Sex(M/F)  ...          838          839          840
652   215         415     Male  ...     0.000000     0.000000     0.000000
653   216         416   Female  ...     0.000000     0.000000     0.000000
654   217         417     Male  ...     0.000000     0.000000     0.000000
655   218         418     Male  ...     0.000000     0.000000     0.000000
656   219         419     Male  ...  2717.364585  2717.786408  2718.201789

[5 rows x 852 columns]

In [18]:
ppg_combained.loc[:,'0':'840']#Looking at the signal feature columns

               0            1  ...          839          840
0    2295.835256  2295.825631  ...     0.000000     0.000000
1    2032.184944  2032.183809  ...     0.000000     0.000000
2    2039.278795  2039.275898  ...     0.000000     0.000000
3    2088.693675  2088.692026  ...     0.000000     0.000000
4    2048.847053  2048.845220  ...     0.000000     0.000000
..           ...          ...  ...          ...          ...
652  2826.329128  2826.313337  ...     0.000000     0.000000
653  2819.321302  2819.313228  ...     0.000000     0.000000
654  2916.837542  2916.827477  ...     0.000000     0.000000
655  2818.571221  2818.562874  ...     0.000000     0.000000
656  2790.289533  2790.282277  ...  2717.786408  2718.201789

[657 rows x 841 columns]

In [19]:
dropindex=[]#variable for storing the indexes to be dropped

In [20]:
for i in range(len(ppg_combained)):
    rowarr=ppg_combained.loc[i,'0':'840']#Storing the signal feature columns
    if sum(rowarr)==0:
        dropindex.append(i)   #Add to dropindex if the sum of rowarr is zero

In [21]:
dropindex #List of indexes to be dropped

[69,
 95,
 98,
 133,
 137,
 161,
 162,
 251,
 259,
 263,
 300,
 306,
 363,
 369,
 372,
 382,
 403,
 413,
 470,
 478,
 482,
 519,
 525,
 582,
 588,
 591,
 601,
 622,
 632]

In [22]:
len(dropindex)

29

In [23]:
ppg_combained.loc[dropindex]#Interpreting at the signals to be dropped

     Num.  subject_ID Sex(M/F)  Age(year)  Height(cm)  ...  836  837  838  839  840
69     70         103   Female         63         153  ...  0.0  0.0  0.0  0.0  0.0
95     96         136   Female         80         156  ...  0.0  0.0  0.0  0.0  0.0
98     99         139   Female         69         150  ...  0.0  0.0  0.0  0.0  0.0
133   134         179   Female         64         151  ...  0.0  0.0  0.0  0.0  0.0
137   138         184     Male         35         175  ...  0.0  0.0  0.0  0.0  0.0
161   162         212     Male         71         155  ...  0.0  0.0  0.0  0.0  0.0
162   163         213     Male         63         169  ...  0.0  0.0  0.0  0.0  0.0
251    33          45     Male         80         165  ...  0.0  0.0  0.0  0.0  0.0
259    41          55     Male         27         181  ...  0.0  0.0  0.0  0.0  0.0
263    45          60     Male         75         160  ...  0.0  0.0  0.0  0.0  0.0
300    82         116     Male         64         165  ...  0.0  0.0  0.0  0.0  0.0
306    88         125   Female         69         155  ...  0.0  0.0  0.0  0.0  0.0
363   145         192   Female         56         158  ...  0.0  0.0  0.0  0.0  0.0
369   151         199   Female         78         158  ...  0.0  0.0  0.0  0.0  0.0
372   154         203   Female         63         153  ...  0.0  0.0  0.0  0.0  0.0
382   164         214     Male         66         172  ...  0.0  0.0  0.0  0.0  0.0
403   185         237     Male         81         168  ...  0.0  0.0  0.0  0.0  0.0
413   195         248   Female         70         156  ...  0.0  0.0  0.0  0.0  0.0
470    33          45     Male         80         165  ...  0.0  0.0  0.0  0.0  0.0
478    41          55     Male         27         181  ...  0.0  0.0  0.0  0.0  0.0
482    45          60     Male         75         160  ...  0.0  0.0  0.0  0.0  0.0
519    82         116     Male         64         165  ...  0.0  0.0  0.0  0.0  0.0
525    88         125   Female         69         155  ...  0.0  0.0  0.0  0.0  0.0
582   145         192   Female         56         158  ...  0.0  0.0  0.0  0.0  0.0
588   151         199   Female         78         158  ...  0.0  0.0  0.0  0.0  0.0
591   154         203   Female         63         153  ...  0.0  0.0  0.0  0.0  0.0
601   164         214     Male         66         172  ...  0.0  0.0  0.0  0.0  0.0
622   185         237     Male         81         168  ...  0.0  0.0  0.0  0.0  0.0
632   195         248   Female         70         156  ...  0.0  0.0  0.0  0.0  0.0

[29 rows x 852 columns]

In [24]:
ppg_combained.drop(dropindex,inplace=True)#Dropping the indexes present in dropindex list

In [25]:
ppg_combained.head()

   Num.  subject_ID Sex(M/F)  Age(year)  Height(cm)  ...  836  837  838  839  840
0     1           2   Female         45         152  ...  0.0  0.0  0.0  0.0  0.0
1     2           3   Female         50         157  ...  0.0  0.0  0.0  0.0  0.0
2     3           6   Female         47         150  ...  0.0  0.0  0.0  0.0  0.0
3     4           8     Male         45         172  ...  0.0  0.0  0.0  0.0  0.0
4     5           9   Female         46         155  ...  0.0  0.0  0.0  0.0  0.0

[5 rows x 852 columns]

In [26]:
ppg_combained.tail()

     Num.  subject_ID Sex(M/F)  ...          838          839          840
652   215         415     Male  ...     0.000000     0.000000     0.000000
653   216         416   Female  ...     0.000000     0.000000     0.000000
654   217         417     Male  ...     0.000000     0.000000     0.000000
655   218         418     Male  ...     0.000000     0.000000     0.000000
656   219         419     Male  ...  2717.364585  2717.786408  2718.201789

[5 rows x 852 columns]

In [27]:
len(ppg_combained)

628

In [28]:
#Storing the resulting dataframe obtained after dropping the dropindex indexes
ppg_combained.to_csv('PPGObtained.csv',index=False)